const reposConstants = {
  FETCH_REPOS: 'FETCH_REPOS',
  FETCH_TOP_REPOS: 'FETCH_TOP_REPOS',
  FETCH_PREVIOUS_REPOS: 'FETCH_PREVIOUS_REPOS',
  FETCH_NEXT_REPOS: 'FETCH_NEXT_REPOS',
  FETCH_CONTRIBUTORS: 'FETCH_CONTRIBUTORS',
  FETCH_PREVIOUS_CONTRIBUTORS: 'FETCH_PREVIOUS_CONTRIBUTORS',
  FETCH_NEXT_CONTRIBUTORS: 'FETCH_NEXT_CONTRIBUTORS',
  FETCH_FIRST_CONTRIBUTORS: 'FETCH_FIRST_CONTRIBUTORS',
  FETCH_LAST_CONTRIBUTORS: 'FETCH_LAST_CONTRIBUTORS',
};

export default reposConstants;
