const reposConstants = {
  FETCH_REPOS: 'FETCH_REPOS',
  FETCH_PREVIOUS_REPOS: 'FETCH_PREVIOUS_REPOS',
  FETCH_NEXT_REPOS: 'FETCH_NEXT_REPOS',
  FETCH_CONTRIBUTORS: 'FETCH_CONTRIBUTORS',
};

export default reposConstants;
